# This notebook is used to export csv files with different views on the data

In [30]:
import pandas as pd
import sqlite3

In [31]:
con = sqlite3.connect("../data/data.sqlite")

In [32]:
SQLJoinEventWithCase = """select e.sorting, e.EVENTTIME, e.ACTIVITY_EN, e.Automation,  c.*, Revenue - Costs as "Profit"
from Pizza_Event e
inner join Pizza_Case c on e._CASE_KEY = c._CASE_KEY
order by sorting"""
df = pd.read_sql(SQLJoinEventWithCase, con)

In [33]:
df

,SORTING,EVENTTIME,ACTIVITY_EN,Automation,_CASE_KEY,Variant,Customer_ID,Revenue,Costs,PizzaType,PizzaSize,CustomerSatisfaction,CostFactor,Weekday,Daytime,DistributionChannel,CustomerLocation,CustomerType,Profit
0,1,15.06.18 09:37,Order by phone,A,1,4,17,10,47,Salami,Small,2,Chef 1,Sunday,21,Deliver Now Holding,Munich District One,Teenager,-37
1,2,15.06.18 09:40,Start preparing pizza,A,1,4,17,10,47,Salami,Small,2,Chef 1,Sunday,21,Deliver Now Holding,Munich District One,Teenager,-37
2,3,15.06.18 09:45,Call Customer,A,1,4,17,10,47,Salami,Small,2,Chef 1,Sunday,21,Deliver Now Holding,Munich District One,Teenager,-37
3,4,15.06.18 09:46,Start preparing pizza,A,1,4,17,10,47,Salami,Small,2,Chef 1,Sunday,21,Deliver Now Holding,Munich District One,Teenager,-37
4,5,15.06.18 09:53,Start baking pizza,B,1,4,17,10,47,Salami,Small,2,Chef 1,Sunday,21,Deliver Now Holding,Munich District One,Teenager,-37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15804,15805,26.07.18 08:14,Order at the counter (shop),A,2000,2,127,10,11,Salami,Small,3,Waiter,Saturday,18,Heropizza Lmtd.,Munich District Four,Teenager,-1
15805,15806,26.07.18 08:14,Start preparing pizza,A,2000,2,127,10,11,Salami,Small,3,Waiter,Saturday,18,Heropizza Lmtd.,Munich District Four,Teenager,-1
15806,15807,26.07.18 08:21,Start baking pizza,A,2000,2,127,10,11,Salami,Small,3,Waiter,Saturday,18,Heropizza Lmtd.,Munich District Four,Teenager,-1
15807,15808,26.07.18 08:32,Baking pizza ready,A,2000,2,127,10,11,Salami,Small,3,Waiter,Saturday,18,Heropizza Lmtd.,Munich District Four,Teenager,-1
15808,15809,26.07.18 08:33,Payment customer,B,2000,2,127,10,11,Salami,Small,3,Waiter,Saturday,18,Heropizza Lmtd.,Munich District Four,Teenager,-1

In [34]:
df["VariantCategorical"] = df["Variant"].map(lambda x: f"Variant {x}") # Make it more comfortable to work with categorical data in PMTK

In [35]:
df.to_csv("../data/PizzaJoinCaseAndEvent.csv")